# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3

exclude: '^assets/'
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.3.2'
  hooks:
    - id: ruff
      args: ['--fix', '--config', 'pyproject.toml'] # we want this to refer to `bdai/pyproject.toml`

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
      language_version: python3.10
    #   args: ['--config', 'pyproject.toml'] # we want this to refer to `bdai/pyproject.toml`
      verbose: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: check-yaml
      args: ['--unsafe'] # details about the unsafe flag:
      # https://github.com/pre-commit/pre-commit-hooks#check-yaml
      # This is the solution proposed to prevent `check-yaml` from failing on custom tags:
      # https://github.com/pre-commit/pre-commit-hooks/issues/701
  -   id: check-added-large-files
      args: ['--enforce-all', '--maxkb', '200']
      # For the `exclude` argument, see https://pre-commit.com/#regular-expressions
      # Make sure to escape strings correctly to ensure literal matches, for example, using Python
      #
      # >>> print(re.escape("path/to-some/file.ext"))
      # path/to\-some/file\.ext
      #
      # `path/to\-some/file\.ext` is the correct regex pattern to match `path/to-some/file.ext` literally.
      # The inverse operation is more cumbersome: https://stackoverflow.com/a/54840284
      exclude: |
        (?x)^(
          docker/ros/web/static/novnc/vendor/browser\-es\-module\-loader/dist/babel\-worker\.js|
          docker/ros/rootfs/usr/local/share/doro\-lxde\-wallpapers/bg.*\.jpg|
          docker/ros/web/yarn\.lock|
          src/modelzoo/detic/lvis_v1_train_cat_info\.json|
          src/modelzoo/edge_grasp_serve/example_pc\.npy
        )$
  -   id: check-toml
  -   id: end-of-file-fixer
  -   id: check-merge-conflict
  -   id: check-executables-have-shebangs
  -   id: check-shebang-scripts-are-executable
  -   id: debug-statements # Ensure we don't commit `import pdb; pdb.set_trace()`
  -   id: trailing-whitespace
  -   id: requirements-txt-fixer


-   repo: https://github.com/ssciwr/clang-format-hook.git
    rev: v12.0.1  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]

-   repo: https://github.com/cpplint/cpplint.git
    rev: 1.6.1
    hooks:
    -   id: cpplint
        args: ['--quiet']
        exclude_types: [cuda]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  -   id: mypy
      args: [--follow-imports=skip, --ignore-missing-imports, --show-error-codes, --pretty, --no-error-summary, --disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]
    #   pass_filenames: true
      additional_dependencies:
      - protobuf
      - types-protobuf
      - types-requests
      - types-simplejson
      - types-ujson
      - types-PyYAML
      - types-toml
      - types-six
      - types-pytz

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  -  id: forbid-binary

# - repo: https://github.com/rhysd/actionlint
#   # only used locally. ensure this matches .github/workflows/actionlint.yml
#   rev: v1.6.27
#   hooks:
#     - id: actionlint
#       args:
#         # allow shellcheck on inline GHA bash
#         # but drop info-level (like glob quoting), it's too noisy + rarely meaningful
#         - "-ignore=shellcheck.*info"
#         # TMP: paths-filter is misconfigured and breaking actionlint https://github.com/rhysd/actionlint/issues/416
#         - -ignore=predicate-quantifier
#         # keep this consistent with the GHA
#         - "-config-file=.github/actions/actionlint/actionlint.yml"

# - repo: https://github.com/stepchowfun/tagref
#   rev: v1.9.1
#   hooks:
#     - id: tagref
#       # version of Rust
#       language_version: 1.76.0
