name: utils
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - xformers
dependencies:
  - python=3.10
  - pip=24.2
  - cuda-toolkit=12.1.0
  - pytorch=2.4.0
  - torchvision=0.19.1
  - pytorch3d=0.7.8
  - h5py=3.7.0
  - hydra-core=1.3.2
  - einops=0.4.1
  - omegaconf=2.3.0
  - tqdm=4.66.6
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - numpy=1.26.4
  - pip:
    - matplotlib==3.8.2
    - opencv-contrib-python==4.9.0.80
    - wandb==0.17.0
    - wandb-osh==1.2.1
    - pandas==2.2.3
    - sapien==2.2.2
    - ipython==8.31.0
    - open3d==0.18.0
    - trimesh==3.23.0
    - transforms3d==0.4.2
    - pdoc3==0.11.5
    - pygame==2.6.1
    - git+https://github.com/WangYixuan12/urdfpy.git
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/WangYixuan12/XMem.git
