name: Generate Documentation

on:
  push:
    branches: [ main ]  # Adjust branch as needed

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository so the workflow has access to your code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies (Sphinx and any project dependencies)
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints

      # Generate the documentation using Sphinx
      - name: Generate Documentation
        working-directory: docs
        run: |
          make html

      # (Optional) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs/_build/html
