name: Generate pdoc Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access your code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: conda_env.yaml
          activate-environment: utils
          use-mamba: true

      # Generate documentation using pdoc3
      - name: Generate Documentation
        run: |
          # Create the output directory if it doesn't exist
          mkdir -p docs
          # Replace "your_module" with your package or module name
          cd src/
          conda run -n utils pdoc --html --force --output-dir ../docs yixuan_utilities

      # (Optional) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs
